import { StyleSheet } from "react-native";

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: "#fff",
    },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 15,
    },
    headerTitle: { fontSize: 20, fontWeight: "700" },
    statusCard: {
        margin: 15,
        borderRadius: 10,
        overflow: "hidden",
        backgroundColor: "#fff",
        elevation: 3,
    },
    statusTopBar: { backgroundColor: "#0047FF", padding: 12 },
    statusTopText: { color: "#fff", fontSize: 18, fontWeight: "700" },
    statusBottom: { paddingVertical: 15, alignItems: "center" },
    statusPending: { fontSize: 18, fontWeight: "800", color: "green" },
    card: {
        margin: 15,
        backgroundColor: "#fff",
        padding: 12,
        borderRadius: 10,
        elevation: 3,
    },
    title: { fontSize: 17, fontWeight: "700", marginBottom: 8 },
    separator: { height: 1, backgroundColor: "#E5E7EB", marginBottom: 12 },
    row: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 14,
    },
    label: { fontSize: 15, fontWeight: "700", color: "#111" },
    value: { fontSize: 15, fontWeight: "600", color: "#555" },
    productHeader: {
        flexDirection: "row",
        backgroundColor: "#CFC9FF",
        borderBottomWidth: 1,
        borderColor: "#D1D5DB",
    },
    productRow: {
        flexDirection: "row",
        borderBottomWidth: 1,
        borderColor: "#D1D5DB",
    },
    cellHead: {
        width: 130,
        textAlign: "center",
        fontWeight: "700",
        paddingVertical: 8,
        borderRightWidth: 1,
        borderColor: "#D1D5DB",
    },
    cell: {
        width: 130,
        textAlign: "center",
        fontWeight: "600",
        paddingVertical: 8,
        borderRightWidth: 1,
        borderColor: "#D1D5DB",
    },
    totalBox: {
        marginTop: 15,
        backgroundColor: "#CFC9FF",
        flexDirection: "row",
        justifyContent: "space-between",
        padding: 14,
        borderRadius: 8,
    },
    totalLabel: { fontSize: 17, fontWeight: "700" },
    totalValue: { fontSize: 17, fontWeight: "700" },
    payBtn: {
        backgroundColor: "#0047FF",
        margin: 15,
        paddingVertical: 15,
        borderRadius: 8,
    },
    payText: {
        textAlign: "center",
        color: "#fff",
        fontSize: 18,
        fontWeight: "700",
    },
    popupOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "rgba(0,0,0,0.45)",
        justifyContent: "center",
        alignItems: "center",
    },
    popupBox: {
        width: "85%",
        backgroundColor: "#fff",
        borderRadius: 18,
        padding: 22,
    },
    popupTitle: { fontSize: 20, fontWeight: "800", textAlign: "center", marginBottom: 14 },
    popupMsg: { fontSize: 16, color: "#222", marginBottom: 4 },
    popupBtnRow: { flexDirection: "row", marginTop: 18 },
    cancelBtn: {
        flex: 1,
        backgroundColor: "#E4E6FF",
        paddingVertical: 12,
        borderRadius: 8,
        marginRight: 10,
        alignItems: "center",
    },
    cancelBtnText: { fontSize: 17, fontWeight: "700", color: "#3238A8" },
    payNowBtn: {
        flex: 1,
        backgroundColor: "#0047FF",
        paddingVertical: 12,
        borderRadius: 8,
        marginLeft: 10,
        alignItems: "center",
    },
    payNowText: { fontSize: 17, fontWeight: "700", color: "#fff" },
    loaderOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "rgba(0,0,0,0.45)",
        justifyContent: "center",
        alignItems: "center",
        zIndex: 999,
    },
    loaderBox: {
        backgroundColor: "#fff",
        padding: 22,
        borderRadius: 15,
        alignItems: "center",
        width: "70%",
    },
});
